import React, { useEffect, useState } from "react";

export default function ValidatePurchaseOrders() {
  const [requests, setRequests] = useState([]);

  useEffect(() => {
    // TODO: Fetch approved requests from backend API
    // Example:
    // fetch("/api/requests?status=APPROVED")
    //   .then(res => res.json())
    //   .then(data => setRequests(data));

    // Dummy data for now
    setRequests([
      {
        id: 1,
        title: "Laptop Purchase",
        description: "Buy 5 laptops for staff",
        amount: 6000,
        status: "APPROVED",
        purchaseOrder: "PO-001.pdf", // Generated by system
        createdBy: "Alice Johnson",
        createdAt: "2025-11-20",
      },
      {
        id: 2,
        title: "Office Chairs",
        description: "Buy 10 ergonomic chairs",
        amount: 2000,
        status: "APPROVED",
        purchaseOrder: "PO-002.pdf",
        createdBy: "Bob Smith",
        createdAt: "2025-11-18",
      },
    ]);
  }, []);

  return (
    <div className="p-6 min-h-screen bg-blue-50">
      <h2 className="text-2xl font-bold mb-6 text-center text-blue-800">
        Generated Purchase Orders
      </h2>

      {requests.length === 0 ? (
        <p className="text-center text-gray-600 mt-6">
          No approved requests found.
        </p>
      ) : (
        <div className="overflow-x-auto bg-white shadow rounded-lg">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-100">
              <tr>
                <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Title</th>
                <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Description</th>
                <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Amount</th>
                <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Purchase Order</th>
                <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Created By</th>
                <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Created At</th>
                <th className="px-4 py-2 text-center text-sm font-semibold text-gray-700">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {requests.map((req) => (
                <tr key={req.id}>
                  <td className="px-4 py-2">{req.title}</td>
                  <td className="px-4 py-2">{req.description}</td>
                  <td className="px-4 py-2">${req.amount}</td>
                  <td className="px-4 py-2">
                    {req.purchaseOrder ? (
                      <a
                        href={`/${req.purchaseOrder}`}
                        className="text-blue-600 underline hover:text-blue-800"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        {req.purchaseOrder}
                      </a>
                    ) : (
                      "-"
                    )}
                  </td>
                  <td className="px-4 py-2">{req.createdBy}</td>
                  <td className="px-4 py-2">{req.createdAt}</td>
                  <td className="px-4 py-2 text-center">
                    <button
                      className="bg-green-500 hover:bg-green-600 text-white px-3 py-1 rounded-md"
                      onClick={() => alert(`Viewing PO: ${req.purchaseOrder}`)}
                    >
                      View
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
